#!/usr/bin/env python3
"""Derive the git-hook repo lists from `config/projects.yaml`.

The hooks are POSIX shell and must keep working with the server down, so they
read a plain one-path-per-line file rather than parsing YAML. That is a
constraint on the *hooks*, not on the installer: this runs once, on the host,
where Python is available.

Keeping the lists hand-written meant two sources of truth for one decision —
"which of my projects does mnemos care about" — free to drift. They are
generated from `projects.yaml` instead.

`paths:` declares path *prefixes* (often subdirectories); a git hook fires at
a repository *root*. Each prefix is therefore walked up to the nearest
enclosing `.git` to get the root the hook will actually see.

Usage:
    ./scripts/derive-hook-repos.py --codebase-root ~/Developments
    ./scripts/derive-hook-repos.py --codebase-root ~/code --print
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "packages"))

from core.projects import load_path_tags  # noqa: E402

DEFAULT_PROJECTS = Path(__file__).resolve().parent.parent / "config" / "projects.yaml"

_HEADER = {
    "repos": (
        "# Mnemos memory-extraction paths (one per line)\n"
        "# post-commit / pre-push only extract memories for repos under these.\n"
    ),
    "index-repos": (
        "# Mnemos code-indexing paths (one per line)\n"
        "# post-merge / post-checkout only index repos under these paths.\n"
        "# Falls back to ./repos when this file is absent.\n"
    ),
}
_GENERATED = "# Generated by scripts/derive-hook-repos.py — edit config/projects.yaml instead.\n"


def git_root_for(path: Path, stop_at: Path) -> Path | None:
    """Nearest ancestor of `path` holding a .git, without escaping `stop_at`."""
    current = path
    while True:
        if (current / ".git").exists():
            return current
        if current == stop_at or current.parent == current:
            return None
        current = current.parent


def derive_roots(projects_config: Path, codebase_root: Path) -> list[str]:
    """Repository roots covering every prefix declared in projects.yaml.

    A prefix whose directory does not exist, or that sits outside any git
    repository, is skipped: a hook could never fire for it anyway.
    """
    roots: set[Path] = set()
    for prefix in load_path_tags(projects_config):
        target = codebase_root / prefix.strip("/")
        if not target.exists():
            continue
        root = git_root_for(target, codebase_root)
        if root is not None:
            roots.add(root)

    # Drop any root nested inside another: the hooks match on path prefix, so
    # the parent already covers it and the child would be dead weight.
    minimal = [
        r for r in roots
        if not any(other != r and _is_under(r, other) for other in roots)
    ]
    return sorted(str(r) for r in minimal)


def _is_under(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--projects-config", default=str(DEFAULT_PROJECTS))
    parser.add_argument(
        "--codebase-root", required=True,
        help="Host directory the projects.yaml prefixes are relative to.",
    )
    parser.add_argument(
        "--config-dir", default=str(Path.home() / ".config" / "mnemos"),
        help="Where to write repos / index-repos.",
    )
    parser.add_argument("--print", action="store_true", dest="print_only",
                        help="Print the derived roots without writing anything.")
    args = parser.parse_args()

    codebase_root = Path(args.codebase_root).expanduser().resolve()
    roots = derive_roots(Path(args.projects_config), codebase_root)

    if not roots:
        print(
            f"No repository root derived from {args.projects_config} under "
            f"{codebase_root} — refusing to write empty lists.",
            file=sys.stderr,
        )
        return 1

    if args.print_only:
        for r in roots:
            print(r)
        return 0

    config_dir = Path(args.config_dir).expanduser()
    config_dir.mkdir(parents=True, exist_ok=True)
    body = "".join(f"{r}\n" for r in roots)
    for name in ("repos", "index-repos"):
        (config_dir / name).write_text(_HEADER[name] + _GENERATED + body, encoding="utf-8")

    print(f"{len(roots)} repository root(s) written to {config_dir}/{{repos,index-repos}}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
